# Generated by Django 6.0.7 on 2026-08-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='session_format',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='session_type',
        ),
    ]
