# Generated by Django 6.0.7 on 2026-08-01 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_stripewebhooklog_paymenttransaction_and_more'),
        ('Provider', '0008_coachprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='providerstripeaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedpaymentmethod',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='provider',
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='providerwallet',
            name='pending_withdrawal',
        ),
        migrations.RemoveField(
            model_name='providerwallet',
            name='total_withdrawn',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Provider.product'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='Payments.servicebooking'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(default='succeeded', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Provider.service'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(default='credit', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProviderBankAccount',
        ),
        migrations.DeleteModel(
            name='ProviderStripeAccount',
        ),
        migrations.DeleteModel(
            name='SavedPaymentMethod',
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
