# Generated by Django on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_servicebooking_refund_id_servicebooking_refund_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
