# Generated by Django 6.0.7 on 2026-08-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_providerapproval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderApproval',
        ),
    ]
