# Generated by Django on 2026-08-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_delete_providerapproval'),
    ]

    operations = [
    ]
