# Generated by Django 6.0.7 on 2026-07-28 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
        ('Provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('one_time', 'One Time Session'), ('package', 'Session Package'), ('monthly', 'Monthly Retainer'), ('discovery', 'Free Discovery Call')], max_length=20)),
                ('session_format', models.CharField(choices=[('video', 'Video Call'), ('audio', 'Audio Call'), ('chat', 'Chat Session')], max_length=20)),
                ('session_duration', models.PositiveIntegerField(help_text='Minutes')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_type', models.CharField(choices=[('instant', 'Instant Booking'), ('approval', 'Coach Approval Required')], default='instant', max_length=20)),
                ('who_is_this_service_for', models.TextField()),
                ('preparation_instructions', models.TextField(blank=True, null=True)),
                ('cancellation_policy', models.CharField(choices=[('flexible', 'Flexible'), ('standard', 'Standard'), ('strict', 'Strict'), ('default', 'Platform Default')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Administration.category')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='Provider.service')),
            ],
        ),
    ]
