# Generated by Django 6.0.7 on 2026-07-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0002_service_clientbenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='session_url',
            field=models.URLField(blank=True),
        ),
    ]
