# Generated by Django 6.0.7 on 2026-08-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='coach/products/'),
        ),
    ]
