# Generated by Django 6.0.7 on 2026-08-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='book_file',
        ),
    ]
