# Generated by Django 6.0.7 on 2026-08-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0007_rename_image_product_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
